Remove unittest2 from install_requires to tests_require
Currently, we are facing failure while debian installing `cqlsh` on python 2.7.

The issue is because of traceback2->unittest2->cqlsh>=5.0.3

where:
```
      File "/lib/python2.7/site-packages/linecache2/tests/inspect_fodder2.py", line 102
        def keyworded(*arg1, arg2=1):
                                ^
    SyntaxError: invalid syntax
```
happens on py27.

The proposed change would not install unittest2 while building the debian.